const v1 = 1;
console.log(v1);
let v2 = 2;
// v2 = 'hello';
console.log(v2);
let v3 = 3;
console.log(v3);
let v4 = 4;
// v4 = 'hello';
console.log(v4);
let v5 = 5;
v5 = 'hello';
console.log(v5);
const arr1 = [];
arr1.push(1);
console.log(arr1);
let v6;
// v6 = 1;
// v6 = new Date;
v6 = [1, 'hello', new Date];
console.log(v6);
export {};
